[package]
name = "algebra"
version = "0.1.0"
authors = ["Christopher Sebastian <csebastian3@gmail.com>"]
edition = "2018"

[dependencies]
kerr = "0.1"
# stacked = { path = "../stacked" }

[profile.bench]
debug = true

