[package]
name = "al"
version = "0.1.4"
authors = ["Christopher Sebastian <csebastian3@gmail.com>"]
license = "MIT"
repository = "https://github.com/likebike/al"
description = """Fast evaluation of algebraic expressions"""
edition = "2018"

[dependencies]
kerr = "0.1"

[profile.bench]
debug = true

[features]
default = ["alpha-keywords"]
alpha-keywords = []  # Enable 'NaN', 'inf', 'and', 'or'
unsafe-vars = []  # tinyexpr-style pointer-based variables.

